# Sistema base
CONFIG_PRINTK=y
CONFIG_UART_CONSOLE=y
CONFIG_CBPRINTF_FP_SUPPORT=y


CONFIG_PINCTRL=y
# Esto le dice a Zephyr que habilite la administración de energía y reloj de los periféricos de NXP
CONFIG_CLOCK_CONTROL=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# I2C
CONFIG_I2C=y
CONFIG_I2C_MCUX=y

# SPI
#CONFIG_SPI=y

# GPIO
CONFIG_GPIO=y

# Threads y RTOS
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=8192

# Math library para sqrtf()
CONFIG_FPU=y
CONFIG_FPU_SHARING=y
CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

# Tamaño de stacks de threads
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

